export function renderHQ() {
  return String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>INSPIRE HQ Preview</title>
<style>
:root{color-scheme:dark;--bg:#07090d;--panel:rgba(10,14,21,.92);--line:rgba(255,255,255,.12);--text:#f5f7fb;--muted:#9aa3b2;--violet:#a64cff;--good:#51e3a4;--warn:#ffd166;--bad:#ff6f7d}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font:13px/1.4 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.app{position:fixed;inset:0;background:#090b0f}.world-wrap{position:absolute;inset:0;overflow:hidden;background:radial-gradient(circle at 50% 20%,#1e1627 0,#0a0d12 56%,#06070a 100%)}.world{position:absolute;width:1664px;height:936px;left:50%;top:50%;transform-origin:50% 50%;will-change:transform;transition:transform .2s ease}.world img{position:absolute;inset:0;width:100%;height:100%;display:block;user-select:none;pointer-events:none}.world-base{z-index:1}.depth-layer{z-index:5;filter:saturate(1.03);pointer-events:none}.depth-atrium{clip-path:polygon(33% 39%,71% 39%,77% 79%,26% 80%)}.depth-reception{clip-path:polygon(35% 69%,74% 69%,79% 100%,22% 100%)}.lightwash{position:absolute;inset:0;z-index:7;pointer-events:none;background:radial-gradient(circle at 53% 54%,rgba(255,191,91,.05),transparent 22%),linear-gradient(180deg,rgba(255,126,59,.03),transparent 38%);mix-blend-mode:screen;animation:breathe 6s ease-in-out infinite}.scanline{position:absolute;inset:0;z-index:8;pointer-events:none;background:linear-gradient(90deg,transparent 0,rgba(166,76,255,.035) 48%,transparent 52%);background-size:180px 100%;animation:scan 12s linear infinite;opacity:.5}
.hotspot{position:absolute;z-index:12;width:48px;height:48px;border-radius:50%;transform:translate(-50%,-50%);border:1px solid rgba(255,255,255,.12);background:rgba(0,0,0,.08);box-shadow:0 0 0 0 rgba(81,227,164,.35);cursor:pointer;transition:.2s ease}.hotspot:hover,.hotspot.active{border-color:rgba(255,255,255,.45);box-shadow:0 0 0 9px rgba(166,76,255,.12)}.hotspot:after{content:"";position:absolute;width:8px;height:8px;border-radius:50%;right:1px;top:1px;background:var(--good);box-shadow:0 0 16px var(--good)}.hotspot.waiting:after{background:var(--warn);box-shadow:0 0 16px var(--warn)}.hotspot.blocked:after{background:var(--bad);box-shadow:0 0 16px var(--bad)}.tag{position:absolute;z-index:13;min-width:112px;transform:translate(-50%,-100%);padding:7px 9px;border-radius:10px;background:rgba(9,12,18,.88);border:1px solid rgba(255,255,255,.14);backdrop-filter:blur(9px);box-shadow:0 8px 28px rgba(0,0,0,.3);pointer-events:none}.tag b{font-size:12px}.tag small{display:block;color:var(--muted);font-size:10px;margin-top:2px}.bubble{position:absolute;z-index:14;max-width:220px;transform:translate(-50%,-100%);padding:9px 11px;border-radius:12px;background:#f6f7fa;color:#11161e;font-size:11px;box-shadow:0 10px 28px rgba(0,0,0,.3)}.bubble.real{border-left:3px solid var(--violet)}.bubble.ambient{background:rgba(245,247,250,.92);opacity:.88}.bubble .kind{display:block;color:#676f7a;font-size:8px;letter-spacing:.12em;text-transform:uppercase;margin-bottom:4px}
.hud{position:absolute;z-index:30;left:20px;top:20px;display:flex;align-items:center;gap:10px;padding:8px 10px;border:1px solid var(--line);border-radius:12px;background:rgba(7,9,13,.76);backdrop-filter:blur(12px)}.logo{width:28px;height:28px;display:grid;place-items:center;border-radius:8px;background:linear-gradient(145deg,#ca61ff,#7b3dff);font-weight:900;font-size:22px}.hud h1{font-size:13px;margin:0}.hud p{margin:1px 0 0;color:var(--muted);font-size:10px}.live{display:inline-flex;align-items:center;gap:6px;margin-left:4px;padding-left:10px;border-left:1px solid var(--line);font-size:10px;color:#c5ccd7}.live i{width:7px;height:7px;border-radius:50%;background:var(--good);box-shadow:0 0 12px var(--good)}.controls{position:absolute;z-index:31;right:20px;top:20px;display:flex;gap:8px}.control{border:1px solid var(--line);background:rgba(7,9,13,.8);color:var(--text);width:38px;height:38px;border-radius:11px;backdrop-filter:blur(12px);cursor:pointer}.control:hover{border-color:rgba(255,255,255,.34)}.legend{position:absolute;z-index:30;left:20px;bottom:20px;padding:10px 12px;border-radius:12px;background:rgba(7,9,13,.76);border:1px solid var(--line);backdrop-filter:blur(12px);color:var(--muted);font-size:10px}.legend strong{color:var(--text)}.drawer{position:absolute;z-index:40;right:18px;top:72px;bottom:18px;width:min(360px,calc(100vw - 36px));transform:translateX(calc(100% + 28px));transition:transform .26s ease;background:rgba(9,12,18,.94);border:1px solid var(--line);border-radius:16px;backdrop-filter:blur(18px);box-shadow:0 30px 80px rgba(0,0,0,.5);overflow:auto}.drawer.open{transform:translateX(0)}.drawer-head{position:sticky;top:0;display:flex;justify-content:space-between;align-items:center;padding:14px 15px;background:rgba(9,12,18,.96);border-bottom:1px solid var(--line)}.drawer-body{padding:15px}.drawer h2{font-size:18px;margin:0}.drawer .role{color:var(--muted);margin:3px 0 15px}.drawer .card{border:1px solid var(--line);border-radius:12px;padding:11px 12px;margin:9px 0;background:rgba(255,255,255,.025)}.drawer .label{font-size:9px;text-transform:uppercase;letter-spacing:.1em;color:#8e98a8;margin-bottom:4px}.drawer .value{font-size:12px}.drawer button{border:1px solid var(--line);background:#141925;color:var(--text);padding:8px 10px;border-radius:9px;cursor:pointer}.drawer button:hover{border-color:#61517a}.close{font-size:16px;width:34px;height:34px}.loading{position:absolute;z-index:50;inset:0;display:grid;place-items:center;background:#080a0e;color:#aab1bc;letter-spacing:.08em;text-transform:uppercase;font-size:11px}.loading.hide{display:none}@keyframes breathe{0%,100%{opacity:.65}50%{opacity:1}}@keyframes scan{from{background-position:0 0}to{background-position:360px 0}}@media(prefers-reduced-motion:reduce){.lightwash,.scanline{animation:none}.world,.drawer{transition:none}}
</style>
</head>
<body>
<div class="app">
  <div class="world-wrap" id="worldWrap">
    <div class="world" id="world">
      <img class="world-base" src="/assets/hq-master.webp" alt="INSPIRE HQ" />
      <div class="lightwash"></div><div class="scanline"></div>
      <div id="agentLayer"></div><div id="speechLayer"></div>
      <img class="depth-layer depth-atrium" src="/assets/hq-master.webp" alt="" aria-hidden="true" />
      <img class="depth-layer depth-reception" src="/assets/hq-master.webp" alt="" aria-hidden="true" />
    </div>
  </div>
  <div class="hud"><div class="logo">✱</div><div><h1>INSPIRE HQ</h1><p>Real agents · real state · living office</p></div><span class="live"><i></i>LIVE</span></div>
  <div class="controls"><button class="control" id="minus">−</button><button class="control" id="home">⌂</button><button class="control" id="plus">+</button></div>
  <div class="legend"><strong>Visual preview.</strong> Master HQ artwork preserved. Real-event overlays are purple-marked; ambient office chatter is not logged as work.</div>
  <aside class="drawer" id="drawer"><div class="drawer-head"><div><div class="label">Agent detail</div><h2 id="drawerTitle">Agent</h2></div><button class="close" id="drawerClose">×</button></div><div class="drawer-body" id="drawerBody"></div></aside>
  <div class="loading" id="loading">Loading INSPIRE HQ…</div>
</div>
<script>
(function(){
  var world=document.getElementById('world'),wrap=document.getElementById('worldWrap'),drawer=document.getElementById('drawer'),state={agents:[],events:[],tasks:[]};
  var scale=1,tx=0,ty=0,drag=false,lastX=0,lastY=0;
  var POS={
    'founder-office':{x:21.5,y:13.5,tagY:9.5,bubbleX:28,bubbleY:13},
    'research':{x:18.2,y:35.5,tagY:31.5,bubbleX:25,bubbleY:34},
    'marketing':{x:18.5,y:51.5,tagY:47.5,bubbleX:25,bubbleY:50},
    'admin':{x:86.5,y:35.2,tagY:31.5,bubbleX:91,bubbleY:34},
    'finance':{x:87.3,y:53.5,tagY:49.5,bubbleX:92,bubbleY:52}
  };
  function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]})}
  function recentEvent(id){for(var i=0;i<state.events.length;i++){var e=state.events[i];if(e.actor_agent_id===id&&['agent_output','message_sent'].indexOf(e.event_type)>=0)return e}return null}
  function eventAge(e){if(!e||!e.ts)return Infinity;return (Date.now()-new Date(e.ts).getTime())/1000}
  function renderAgents(){var a=document.getElementById('agentLayer'),s=document.getElementById('speechLayer'),html='',speech='';state.agents.forEach(function(agent){var p=POS[agent.id];if(!p)return;html+='<button class="hotspot '+esc(agent.status)+'" aria-label="'+esc(agent.name)+'" data-agent="'+esc(agent.id)+'" style="left:'+p.x+'%;top:'+p.y+'%"></button><div class="tag" style="left:'+p.x+'%;top:'+p.tagY+'%"><b>'+esc(agent.id==='founder-office'?'Can':agent.name)+'</b><small>'+esc(agent.status)+' · '+esc(agent.department)+'</small></div>';var ev=recentEvent(agent.id);if(ev&&eventAge(ev)<120){speech+='<div class="bubble real" style="left:'+p.bubbleX+'%;top:'+p.bubbleY+'%"><span class="kind">real event</span>'+esc(ev.summary)+'</div>'}});var admin=POS.admin;speech+='<div class="bubble ambient" style="left:'+(admin.x-6)+'%;top:'+(admin.y+7)+'%"><span class="kind">office</span>Checking the floor.</div>';a.innerHTML=html;s.innerHTML=speech}
  function fit(){var sw=wrap.clientWidth/1664,sh=wrap.clientHeight/936;scale=Math.min(sw,sh);tx=0;ty=0;apply()}
  function apply(){world.style.transform='translate(calc(-50% + '+tx+'px),calc(-50% + '+ty+'px)) scale('+scale+')'}
  function zoom(f){scale=Math.max(.45,Math.min(2.2,scale*f));apply()}
  function openAgent(id){var agent=state.agents.find(function(x){return x.id===id});if(!agent)return;document.querySelectorAll('.hotspot').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-agent')===id)});var task=state.tasks.find(function(t){return t.owner_agent_id===id&&t.status!=='done'}),ev=recentEvent(id);document.getElementById('drawerTitle').textContent=id==='founder-office'?'Can · Founder':agent.name;document.getElementById('drawerBody').innerHTML='<div class="role">'+esc(agent.department)+'</div><div class="card"><div class="label">Current state</div><div class="value">'+esc(agent.status)+' — '+esc(agent.status_reason||'No reason reported')+'</div></div><div class="card"><div class="label">Current task</div><div class="value">'+esc(task?task.title:'No active task')+'</div></div><div class="card"><div class="label">Latest real event</div><div class="value">'+esc(ev?ev.summary:'No recent output/message event')+'</div></div><div class="card"><div class="label">Truth boundary</div><div class="value">Ambient office chatter is visual only and is never written as agent work.</div></div>';drawer.classList.add('open')}
  async function load(){try{var r=await fetch('/api/bootstrap',{cache:'no-store'}),d=await r.json();state=d;renderAgents();document.getElementById('loading').classList.add('hide')}catch(e){document.getElementById('loading').textContent='Preview failed to load'}}
  document.addEventListener('click',function(e){var h=e.target.closest('[data-agent]');if(h)openAgent(h.getAttribute('data-agent'))});
  document.getElementById('drawerClose').onclick=function(){drawer.classList.remove('open');document.querySelectorAll('.hotspot').forEach(function(x){x.classList.remove('active')})};document.getElementById('plus').onclick=function(){zoom(1.12)};document.getElementById('minus').onclick=function(){zoom(.89)};document.getElementById('home').onclick=fit;
  wrap.addEventListener('wheel',function(e){e.preventDefault();zoom(e.deltaY<0?1.08:.92)},{passive:false});wrap.addEventListener('pointerdown',function(e){drag=true;lastX=e.clientX;lastY=e.clientY;wrap.setPointerCapture(e.pointerId)});wrap.addEventListener('pointermove',function(e){if(!drag)return;tx+=e.clientX-lastX;ty+=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;apply()});wrap.addEventListener('pointerup',function(){drag=false});window.addEventListener('resize',fit);fit();load();
})();
</script>
</body></html>`;
}
